let mySprite: Sprite = null
let player_1: Sprite = null
tiles.setCurrentTilemap(tilemap`level3`)
for (let value of tiles.getTilesByType(assets.tile`myTile1`)) {
    player_1 = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    player_1.image.replace(14, randint(3, 10))
    tiles.setTileAt(value, assets.tile`myTile`)
    tiles.placeOnTile(player_1, value)
    sprites.setDataNumber(player_1, "homeX", player_1.x)
    sprites.setDataNumber(player_1, "homeY", player_1.y)
    sprites.setDataString(player_1, "team", "left")
    sprites.setDataNumber(player_1, "GoalX", tiles.getTilesByType(assets.tile`myTile4`)[0].x)
    sprites.setDataNumber(player_1, "goalY", tiles.getTilesByType(assets.tile`myTile4`)[0].y)
}
for (let value of tiles.getTilesByType(assets.tile`myTile2`)) {
    player_1 = sprites.create(img`
        . . . . f f f f f . . . . . . . 
        . . . f e e e e e f . . . . . . 
        . . f d d d d e e e f . . . . . 
        . c d f d d f d e e f f . . . . 
        . c d f d d f d e e d d f . . . 
        c d e e d d d d e e b d c . . . 
        c d d d d c d d e e b d c . f f 
        c c c c c d d d e e f c . f e f 
        . f d d d d d e e f f . . f e f 
        . . f f f f f e e e e f . f e f 
        . . . . f e e e e e e e f f e f 
        . . . f e f f e f e e e e f f . 
        . . . f e f f e f e e e e f . . 
        . . . f d b f d b f f e f . . . 
        . . . f d d c d d b b d f . . . 
        . . . . f f f f f f f f f . . . 
        `, SpriteKind.Player)
    player_1.image.replace(13, randint(1, 10))
    tiles.setTileAt(value, assets.tile`myTile`)
    tiles.placeOnTile(player_1, value)
    sprites.setDataNumber(player_1, "homeX", player_1.x)
    sprites.setDataNumber(player_1, "homeY", player_1.y)
    sprites.setDataString(player_1, "team", "left")
    sprites.setDataNumber(player_1, "GoalX", tiles.getTilesByType(assets.tile`myTile5`)[0].x)
    sprites.setDataNumber(player_1, "goalY", tiles.getTilesByType(assets.tile`myTile5`)[0].y)
}
if (Math.percentChance(50)) {
    mySprite = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff2222ff........
        .......f22222222f.......
        .......f22222222f.......
        ......f2222222222f......
        ......f2222222222f......
        ......f2222222222f......
        ......f222fb22222f......
        ......f222fc22222f......
        .......f22222222f.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    mySprite.setPosition(randint(48, 136), randint(20, 100))
} else {
    mySprite = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff9999ff........
        .......f99999999f.......
        .......f99999999f.......
        ......f9999999999f......
        ......f9999999999f......
        ......f9999999999f......
        ......f999fb99999f......
        ......f999fc99999f......
        .......f99999999f.......
        .......f9999ffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    mySprite.setPosition(randint(48, 136), randint(20, 100))
}
